version: '3.8'

services:
  ambev.developerevaluation.database:
    image: postgres:13
    container_name: ambev_developer_evaluation_database
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432"

  ambev.developerevaluation.nosql:
    image: mongo:8.0
    container_name: ambev_developer_evaluation_nosql
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
    ports:
      - "27017"

  ambev.developerevaluation.cache:
    image: redis:7.4.1-alpine
    container_name: ambev_developer_evaluation_cache
    command: redis-server --requirepass ev@luAt10n
    ports:
      - "6379"

  ambev.developerevaluation.webapi:
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    container_name: ambev_developer_evaluation_webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ambev.developerevaluation.database
      - ambev.developerevaluation.nosql
      - ambev.developerevaluation.cache
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh ambev.developerevaluation.database:5432 -- ./wait-for-it.sh ambev.developerevaluation.cache:6379 -- ./wait-for-it.sh ambev.developerevaluation.nosql:27017 -- dotnet ef database update --no-build --context ApplicationDbContext --project src/Ambev.DeveloperEvaluation.WebApi/Ambev.DeveloperEvaluation.WebApi.csproj && dotnet Ambev.DeveloperEvaluation.WebApi.dll"]
